### ISSUE TITLE
Python 2.x support

### ISSUE THREAD

**Issue by rmc3** [theherk/pinkopy#30]
I'm working on a project for which Python 2.x support from this package would be super helpful. I'm currently diving down the rabbit hole of changes that would be necessary to make this work with Python 2.x. 

In the event that I'm successful in getting it working, would there be interest in having those changes contributed?

**Comment by theherk** [comment]
Most definitely. We are moving away from Commvault, but this package is a great start to a full api wrapper for it. As long as your contributions are written neatly, documented, Python 3 first 2 second, and tests pass, I will absolutely take the PR.

**Comment by rmc3** [comment]
@theherk The specific use case involves using pinkopy in conjunction with a Salt runner to orchestrate post-client install configuration via the Commvault API. I notice that on the site linked from your GitHub profile, you mention working with Saltstack. Have you attempted to use pinkopy in the same context as Salt? If so, how have you gotten around the issue of using pinkopy with Salt when Salt does not support Python 3?

**Comment by theherk** [comment]
Oh interesting. We use them separately. We only use the Commvault api to verify the status of backups. We do use Saltstack to configure the client, but we do it via states that do not use the api. You idea sounds like a good one.

**Comment by theherk** [comment]
Fixed in #31.
